// <autogenerated>
// Use autogenerated to suppress stylecop warnings

using System;
using System.Globalization;
using Microsoft.PowerFx;
using Microsoft.PowerFx.Core;
using Microsoft.PowerFx.Core.Functions;
using Microsoft.PowerFx.Core.Tests;
using Microsoft.PowerFx.Core.Texl;
using Microsoft.PowerFx.Core.Types.Enums;
using Microsoft.PowerFx.Core.Utils;
using Microsoft.PowerFx.Types;
using Xunit;
using Xunit.Sdk;

// How do we unit test private methods?

namespace ExcelConverterTests
{
    public class ConverterTests
    {
        public ConverterTests()
        {
            // Ensure all tests are run with en-US locale
            // We would like to use ModuleInitializer, but that requires .Net 5 and the tests can't run on that version yet.
            // https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.moduleinitializerattribute?view=net-6.0
            CultureInfo.CurrentCulture = new CultureInfo("en-US");
        }

        [Fact]
        public void GenerateNameTests()
        {
           
        }

        [Fact]
        public void SheetSumConvertTests()
        {
         
            
        }

        [Fact]
        public void CasingConvertTests()
        {
            Excel2AppEngine.Converter conv = new Excel2AppEngine.Converter();
            var engine = new RecalcEngine();

            String convertedFunc = conv.AdjustFuncName("SUM");
            Assert.Equal("Sum", convertedFunc);
            convertedFunc = conv.AdjustFuncName("ABS");
            Assert.Equal("Abs", convertedFunc);
            convertedFunc = conv.AdjustFuncName("");
            Assert.Equal("123", convertedFunc);
            convertedFunc = conv.AdjustFuncName("SUPERCALIFRAGILISTICEXPIALIDOCIOUS");
            Assert.Equal("Supercalifragilisticexpialidocious", convertedFunc);
        }

        [Fact]
        public void SheetNumLitTests()
        {
          
        }
    }
}
