// <autogenerated>
// Use autogenerated to suppress stylecop warnings 

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Office2016.Drawing.Command;
using Microsoft.PowerFx;
using Microsoft.PowerFx.Core;
using Microsoft.PowerFx.Syntax;
using Microsoft.PowerFx.Types;

namespace ExcelConverter
{
    public class Utils
    {
        private String ConvertFormula(String formula)
        {
            return formula;
        }

        // Expands a range, outputting a string which is a comma-separated list of cells
        // Eg. ExpandRange('A', 3, 'B', 5) -> "A3, A4, A5, B3, B4, B5"
        // what happens when excel gets to ~30 columns? it might break        
        public static String ExpandRange(char rangeStartChar, int rangeStartNum, char rangeEndChar, int rangeEndNum, String sheetName)
        {
            StringBuilder str = new StringBuilder("");
 
            // Iterate through the whole range (eg. A4 to C7) 
            // Expand the whole range with a nested for loop, appending to str
            for (int i = (int)rangeStartChar; i <= (int)rangeEndChar; i++)
            {
                for (int j = rangeStartNum; j <= rangeEndNum; j++)
                {
                    // If this is the last cell to expand, skip comma separation
                    if (i == (int)rangeEndChar && j == rangeEndNum)
                    {
                        String newVar = GenerateName(sheetName, $"{(char)i}{j}");
                        str.Append(newVar);
                    }
                    else
                    {
                        String newVar = GenerateName(sheetName, $"{(char)i}{j}, ");
                        str.Append(newVar);
                    }
                }
            }
         
            return str.ToString();
        }

        // Given a binary op node containing a range, expand range and interpolate the opString and other node
        // Returns a List of strings
        // example output: ["5 + Sheet1_C3", "5 + Sheet1_C4", ... "5 + Sheet1_D8", "5 + Sheet1_D9"]
        public static List<String> Interpolate(String leftStr, String rightStr, String opString, Match leftMatch, Match rightMatch, String sheetName)
        { 
            var strList = new List<String>();

            // If both left and right are ranges, interpolate them together
            if (leftMatch.Success && rightMatch.Success)
            {
                // What letter and number the left range starts with and ends with
                // eg. for A3:B6 startChar is A, startNum is 3 and endNum is B, endNum is 6

                Range leftRange = new Range(leftMatch);
                Range rightRange = new Range(rightMatch);  

                // if there is a size mismatch between the two ranges we need to throw an exception
                int leftRangeSize = (leftRange.endChar - leftRange.startChar + 1) * (leftRange.endNum - leftRange.startNum + 1);
                int rightRangeSize = (rightRange.endChar - rightRange.startChar + 1) * (rightRange.endNum - rightRange.startNum + 1);
                if (leftRangeSize != rightRangeSize)
                {
                    throw (new Exception("ERROR: MISMATCH BETWEEN TWO RANGE SIZES IN BINARY OPERATOR"));
                }

                // Iterate through the letters (A-Z) and numbers of the range
                // i, j are char, num of each of left range's cells ; k, j are char, num of right's
                int k = (int)rightRange.startChar;
                int l = (int)rightRange.startNum;
                for (int i = (int)leftRange.startChar; i <= (int)leftRange.endChar; i++)
                {
                    l = (int)rightRange.startNum;
                    for (int j = leftRange.startNum; j <= leftRange.endNum; j++)
                    {
                        // Have two matching cells from the expanded range, then
                        // make each cell pair into variable names for PowerFX compatibility
                        String leftVar = Utils.GenerateName(sheetName, $"{(char)i}{j}");
                        String rightVar = Utils.GenerateName(sheetName, $"{(char)k}{l}");

                        // Interpolate with the original operator used for 
                        strList.Add($"{leftVar} {opString} {rightVar}");
                        l++;
                    }

                    k++;
                }

            }
            else if (leftMatch.Success) // if left is a range, right isn't
            {
                Range range = new Range(leftMatch);
             
                // Iterate through the whole range (eg. A4 to C7) 
                // Expand the whole range with a nested for loop, appending to str
                for (int i = (int)range.startChar; i <= (int)range.endChar; i++)
                {
                    for (int j = range.startNum; j <= range.endNum; j++)
                    {
                        String newVar = Utils.GenerateName(sheetName, $"{(char)i}{j}");
                        strList.Add($"{newVar} {opString} {rightStr}");
                    }
                }
            }
            else if (rightMatch.Success) // right is a range but left isn't
            {
                Range range = new Range(rightMatch);

                // Iterate through the whole range (eg. A4 to C7) 
                // Expand the whole range with a nested for loop, appending to str
                for (int i = (int)range.startChar; i <= (int)range.endChar; i++)
                {
                    for (int j = range.startNum; j <= range.endNum; j++)
                    {
                        String newVar = Utils.GenerateName(sheetName, $"{(char)i}{j}");
                        strList.Add($"{leftStr} {opString} {newVar}");
                    }
                }
            }

            return strList;
        }

        public static void ProcessDynamicRange(ExcelParser.ParsedCell currCell, List<String> interpolatedList, Match leftMatch, Match rightMatch)
        {
            Range rg = leftMatch.Success ? new Range(leftMatch) : new Range(rightMatch);

            Match matchCurrCell;
            Utils.TryGetCellMatch(currCell.CellId, out matchCurrCell);

            // Iterate through the letters (A-Z) and numbers of the range
            // i, j are char, num of each of left range's cells ; k, l are char, num of right's
            char currCellChar = char.Parse(matchCurrCell.Groups[1].Value);
            int currCellNum = int.Parse(matchCurrCell.Groups[2].Value);
            int k = (int)currCellChar;
            int l = (int)currCellNum;
            for (int i = (int)rg.startChar; i <= (int)rg.endChar; i++)
            {
                l = (int)currCellNum;
                for (int j = rg.startNum; j <= rg.endNum; j++)
                {
                    String currCellId = "" + (char)k + l;

                    int currIteration = (i - rg.startChar) * (rg.endNum - rg.startNum + 1) + (j - rg.startNum + 1);
                    String newCellFormula = interpolatedList[currIteration - 1]; // index out of range
                    Converter.outputList.Add( new ExcelPfxResponse { CellId = currCellId, Formula = Utils.CreateVariable(currCell.SheetName, currCellId, newCellFormula) });
                    Converter.processedSet.Add(currCellId);

                    l++;
                }
                k++;
            }
        }

        private void ReplaceVar(String definedName)
        {

        }

        public static String CreateVariable(String sheetName, String cellNum, String variableValue)
        {
            String varName = GenerateName(sheetName, cellNum);
            return varName + " = " + variableValue;
        }

        public static String CreateVariable(String sheetName, String cellNum, TexlNode node)
        {
            return CreateVariable(sheetName, cellNum, node.ToString());
        }

        // Generate the generic PowerFX default varuabke name (eg. "sheet1_C8") for a given sheetName and cell
        // Eg. Cell B2 on Sheet1 -> Sheet1_B2
        // If we have a defined name established for this in our map, we use that instead
        public static String GenerateName(String sheetName, String cellNum)
        {
            if (sheetName == null || sheetName == "" || cellNum == null || cellNum == "") return "";

            // If a defined name "eg. Variable1" was passed in for cellNum, return it immediately
            // Note: potentially inefficient time complexity?
            if (Converter.definedNamesMap.ContainsValue(cellNum)) return cellNum;

            String genericName = RemoveAllWhitespace(sheetName) + "_" + cellNum;
            String definedName = null;

            // Automatically correct all references to a defined name's cell to the actual defined name
            // eg. Sheet1_C8 is assigned the variable name Variable1. If Sheet1_C8 is referenced in a formula,
            // we will output Variable1 instead
            if (Converter.definedNamesMap.TryGetValue(genericName, out definedName))
            {
                return definedName;
            }
            else
            {
                return genericName;
            }
        }

        public static String RemoveAllWhitespace(String text)
        {
            return Regex.Replace(text, @"\s+", String.Empty);
        }

        // accepts all caps Excel function, converts to PowerFX style function name
        // EG: SUM -> Sum
        public static String AdjustFuncName(String funcName)
        {
            // Make the function name all lowercase and then capitalize the first letter
            char[] retn = (funcName.ToLower()).ToCharArray();
            try
            {
                retn[0] = char.ToUpper(retn[0]);
            }
            catch (IndexOutOfRangeException e)
            {
                // function has no name (is invalid) as indicated by retn[0] not existing
                Console.WriteLine("ERROR {0}: \"{1}\" passed as function name, returning empty string", e.Message, funcName);
                return "";
            }

            return new string(retn);
        }
     
        // Converts a BinaryOp enum value to the actual BinaryOp char
        public static String ConvertBinaryOp(BinaryOp op)
        {
            return binaryOpMap[op];
        }

        // Converts a UnaryOp enum value to the actual UnaryOp char
        public static String ConvertUnaryOp(UnaryOp op)
        {
            return unaryOpMap[op];
        }

        // Reformat range colon, replacing with text for parsing later on
        // eg. A4:C9 -> A4_RANGE_C9
        public static String ReformatRange(String input)
        {
            return colonRangeRegex.Replace(input, "$1_RANGE_$2");
        }

        // Takes in a range eg. "A4:C9" and returns its corresponding range object
        public static Range DecomposeRange(String strInput)
        {
            Match match = decomposeColonRangeRegex.Match(strInput);

            if (!match.Success) return null;

            Range output = new Range(char.Parse(match.Groups[1].Value), int.Parse(match.Groups[2].Value), 
                char.Parse(match.Groups[3].Value), int.Parse(match.Groups[4].Value));

            return output;
        }

        // Takes in a FirstNameNode (input) and Match object (output)
        // Returns TRUE if successfully found the regex match, FALSE if not
        // Looking for A3_RANGE_C8 style pattern that is NOT in quotes
        public static bool TryGetRangeMatch(FirstNameNode node, out Match matchOutput)
        {
            // By default rangeString is the text/name of the firstNameNode
            // If we recognize rangeString as a defined range, then we sub in the A3_RANGE_C8 style pattern
            String rangeString = node.Ident.Name.Value;
            if (Converter.definedRangesMap.ContainsKey(node.Ident.Name.Value)) rangeString = Converter.definedRangesMap[node.Ident.Name.Value];

            matchOutput = parsedRangeRegex.Match(rangeString);
            return matchOutput.Success;
        }

        // Takes in a BinaryOpNode and outputs Match objects for left AND right operands
        // Returns TRUE if any Regex match has been found in either left or right
        // Looking for A3_RANGE_C8 style pattern that is NOT in quotes
        public static bool TryGetRangeMatch(BinaryOpNode node, String leftStr, String rightStr, out Match matchOutLeft, out Match matchOutRight)
        {
            // If we recognize leftStr/rightStr as a defined range, then sub in the A3_RANGE_C8 style pattern
            if (Converter.definedRangesMap.ContainsKey(leftStr)) leftStr = Converter.definedRangesMap[leftStr];
            if (Converter.definedRangesMap.ContainsKey(rightStr)) rightStr = Converter.definedRangesMap[rightStr];

            matchOutLeft = parsedRangeRegex.Match(leftStr);
            matchOutRight = parsedRangeRegex.Match(rightStr);

            return matchOutLeft.Success || matchOutRight.Success;
        }

        public static bool TryGetCellMatch(String cellId, out Match matchOut)
        {
            matchOut = currCellRegex.Match(cellId);
            return matchOut.Success;
        }

        // Takes in a defined name object and extracts the sheet and cell that it corresponds to
        public static String ParseDefinedName(ExcelParser.ParsedDefinedNames definedName)
        {
            Match match = definedNameRegex.Match(definedName.Value);

            if (!match.Success) return null;

            String sheetName = match.Groups[2].Value;
            String cellId = match.Groups[4].Value + match.Groups[5].Value;
            return GenerateName(sheetName, cellId);
        }

        // Takes in a definedName representing a range and extracts range information
        // However, does NOT RETURN SHEET DATA
        public static String ParseDefinedRange(ExcelParser.ParsedDefinedNames definedRange)
        {
            Match match = definedRangeRegex.Match(definedRange.Value);

            if (!match.Success) return null;

            String cell1 = match.Groups[4].Value + match.Groups[5].Value;
            String cell2 = match.Groups[6].Value + match.Groups[7].Value;
            return cell1 + "_RANGE_" + cell2;
        }

        public static String QuoteWrap(String input)
        {
            return "\"" + input + "\"";
        }

        // Takes in a formula that may or may not have a reference to a table in it
        // and converts the table reference, if there is one, to a range
        public static String TableToRange(String formula, ExcelParser.ParsedCell cell)
        {
            // If external table ref regex doesn't match, we try internal table ref
            String retn = formula;
            if (!ExternalTableRefToRange(formula, out retn))
            {
                InternalTableRefToRange(formula, cell, out retn);
            }
         
            // If neither of the regexes match, retn defaults to formula anyway
            // If one of the regexes match, we return the modified result 
            return retn;
        }

        // Takes in an external table reference (ie. a table with NO "@" reference to THIS ROW, THIS COL)
        // Example input: SUM(Table1[[Column1]:[Column2]])
        // If regex match is successful, converts outputs a range like "B4:C6" and returns true
        public static bool ExternalTableRefToRange(String formula, out String output)
        {
            Match match = externalTableRefRegex.Match(formula);
            output = formula;

            if (!match.Success) return false;

            String tableName = match.Groups[1].Value;
            String column1 = match.Groups[2].Value;
            String column2 = match.Groups[3].Value;

            ExcelParser.ParsedTable tableObj = null;

            // If this isn't a valid table name, just return the unmodified formula
            if (!Converter.tableMap.TryGetValue(tableName, out tableObj)) return false;

            ExcelParser.ParsedTableColumn column1Obj = null;
            ExcelParser.ParsedTableColumn column2Obj = null;

            tableObj.ColumnMap.TryGetValue(column1, out column1Obj);
            tableObj.ColumnMap.TryGetValue(column2, out column2Obj);

            String constructedRange = "";
            // If match found for column1 AND column2
            if (column1Obj != null && column2Obj != null)
            {
                // Since there are two columns being referenced, our range is the column 1 start to the column 2 end
                constructedRange = column1Obj.ColumnSpan.GetStartCellString() + ":" + column2Obj.ColumnSpan.GetEndCellString();
            }
            else // If match only found for column1
            {
                // Since there is only one columns being referenced, our range is the same as column1's span
                constructedRange = column1Obj.ColumnSpan.GetRangeString();
            }

            output = Regex.Replace(formula, externalTableRefRegex.ToString(), constructedRange);
            return true;
        }

        // Takes in an internal table reference (ie. a table referring with @ to THIS ROW, THIS COL)
        // Example input: SUM(Table1[@[Column1]:[Column3]])
        // If regex match is successful, converts outputs a range like "B4:D4" and returns true
        public static bool InternalTableRefToRange(String formula, ExcelParser.ParsedCell cell, out String output)
        {
            Match match = internalTableRefRegex.Match(formula);
            output = formula;

            if (!match.Success) return false;

            String tableName = match.Groups[1].Value;
            String operationAxis = match.Groups[2].Value; 
            String column1 = match.Groups[3].Value;
            String column2 = match.Groups[4].Value;

            ExcelParser.ParsedTable tableObj = null;

            // If this isn't a valid table name, just return the unmodified formula
            if (!Converter.tableMap.TryGetValue(tableName, out tableObj)) return false;

            ExcelParser.ParsedTableColumn column1Obj = null;
            ExcelParser.ParsedTableColumn column2Obj = null;

            tableObj.ColumnMap.TryGetValue(column1, out column1Obj);
            tableObj.ColumnMap.TryGetValue(column2, out column2Obj);

            String constructedRange = "";
            Match cellMatch = currCellRegex.Match(cell.CellId);
            int currRowNum = int.Parse(cellMatch.Groups[2].Value); // row the current cell is on
            // If match found for column1 AND column2
            if (column1Obj != null && column2Obj != null)
            {
                // With two columns being referenced, range start is column 1's cell that lies on the current row
                // by the same reasoning, range end is column 2's cell that lies on the same row
                String column1SpanStart = column1Obj.ColumnSpan.startChar + currRowNum.ToString();
                String column2SpanEnd = column2Obj.ColumnSpan.endChar + currRowNum.ToString();
                constructedRange = column1SpanStart + ":" + column2SpanEnd;
            }
            else // If match only found for column1
            {
                // In this case, we actually only have a singular cell which is column 1's cell that lies on the current row
                constructedRange = column1Obj.ColumnSpan.startChar.ToString() + currRowNum;
            }

            output = Regex.Replace(formula, internalTableRefRegex.ToString(), constructedRange);
            return true;
        }

        // Corrects Excel function names to the proper PowerFx equivalent name
        // Eg. VLOOKUP -> LOOKUP
        public static String AlignFunctionName(String functionName)
        { 
            if (functionName == null) return null;

            // If we have a match (there's a name switch that needs to be made)
            // Then we return the proper name
            String output = "";
            if (functionNameMap.TryGetValue(functionName, out output)) return output;

            return functionName;
        }


        // Takes in a parsed table object and builds an output table
        // Example output: Table({Column1=B1, Column2=B2, Column3=B3, Column4=B4}, {Column1=C1, Column2=C2, Column3=C3, Column4=C4})
        public static String BuildTableOutput(ExcelParser.ParsedTable tableInput)
        {
            StringBuilder sb = new StringBuilder();

            sb.Append("Table(");

            // Get the starting and ending columns for this table's range
            Range tableRange = DecomposeRange(tableInput.Range);

            // Iterate to build table output, adding to the output string
            for (int row = tableRange.startNum + 1; row <= tableRange.endNum; row++)
            {
                sb.Append("{");

                for (char col = tableRange.startChar; col <= tableRange.endChar; col++)
                {
                    // calculate 1-indexed colNum so we know what is eg. column 1, column 2, column 3
                    int colNum = col - tableRange.startChar + 1;

                    String varName = GenerateName(tableInput.SheetName, col + row.ToString());
                    String columnName = "Column" + colNum;

                    if (Converter.definedNamesMap.ContainsKey(varName)) varName = Converter.definedNamesMap[varName];

                    sb.Append(columnName + "=" + varName);

                    // Add comma as separator unless we're at the last column
                    if (col < tableRange.endChar) sb.Append(", ");
                }

                sb.Append("}");

                // Add comma as a separator unless we're at the last row
                if (row < tableRange.endNum)
                {
                    sb.Append(", ");
                }
            }
            sb.Append(")");

            return sb.ToString();
        }

        private static Regex externalTableRefRegex = new Regex(@"(\w+)\[+(\w+)\]:?\[?(\w+)?\]{0,2}(?=([^""']*[""'][^""']*[""'])*[^""']*$)");

        private static Regex internalTableRefRegex = new Regex(@"(\w+)\[+\#(.+)\],\[(\w+)\]:?\[?(\w+)?\]{0,2}");

        // regex that detects a A3:C7 style range, ignoring if it is within quotes
        private static Regex colonRangeRegex = new Regex(@"([A-Z]\d+):([A-Z]\d+)(?=([^""']*[""'][^""']*[""'])*[^""']*$)");

        private static Regex decomposeColonRangeRegex = new Regex(@"([A-Z])(\d+):([A-Z])(\d+)(?=([^""']*[""'][^""']*[""'])*[^""']*$)");

        private static Regex parsedRangeRegex = new Regex(@"([A-Z])(\d+)_RANGE_([A-Z])(\d+)(?=([^""']*[""'][^""']*[""'])*[^""']*$)");

        private static Regex currCellRegex = new Regex(@"([A-Z])(\d+)");

        private static Regex definedNameRegex = new Regex(@"(['']?)([^'']+)(['']?)!\$([A-Z])\$(\d+)(?!.)");

        private static Regex definedRangeRegex = new Regex(@"(['']?)([^'']+)(['']?)!\$([A-Z])\$(\d+):\$([A-Z])\$(\d+)");

        private static Dictionary<String, String> functionNameMap = new Dictionary<String, String>()
            {
                {"VLOOKUP", "LOOKUP"},
                {"XLOOKUP", "LOOKUP"}
            };

        private static Dictionary<BinaryOp, String> binaryOpMap = new Dictionary<BinaryOp, String>()
            {
                {BinaryOp.Or, "||"},
                {BinaryOp.And, "&&"},
                {BinaryOp.Concat, "&"},
                {BinaryOp.Add, "+"},
                {BinaryOp.Mul, "*"},
                {BinaryOp.Div, "/"},
                {BinaryOp.Power, "^"},
                {BinaryOp.Equal, "="},
                {BinaryOp.NotEqual, "!="},
                {BinaryOp.Less, "<"},
                {BinaryOp.LessEqual, "<="},
                {BinaryOp.Greater, ">"},
                {BinaryOp.GreaterEqual, ">="},
                {BinaryOp.In, "IN"},
                {BinaryOp.Exactin, "EXACTIN"},
                {BinaryOp.Error, "ERROR"}
            };

        private static Dictionary<UnaryOp, String> unaryOpMap = new Dictionary<UnaryOp, String>()
            {
                {UnaryOp.Not, "!"},
                {UnaryOp.Minus, "-"},
                {UnaryOp.Percent, "%"}
            };
    }
}
